# Nome da Aplicação
spring.application.name=suprimentos-ti

# Conexão com o Banco (Atenção à porta 5433 que é a do seu Docker Local)
spring.datasource.url=jdbc:postgresql://localhost:5433/suprimentos_ti
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# (Coloque a mesma senha que você usa no Helpdesk)

# Configurações do JPA/Hibernate
# create-drop: Cria as tabelas quando liga, apaga quando desliga (Bom para testes iniciais)
# update: Apenas atualiza o banco se você mudar o código (Usaremos este mais tarde)
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console (bom para aprender o que o Java está fazendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true