services:
  # 1. BANCO DE DADOS
  db:
    image: postgres:15-alpine
    container_name: helpdesk_db
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # O banco primário criado junto com o container é o do Next.js
      POSTGRES_DB: helpdesk
    ports:
      - "5433:5432" # A porta 5433 fica exposta para você usar o DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. HELPDESK (NEXT.JS)
  web:
    container_name: helpdesk_web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_ESTOQUE_TOKEN: ${NEXT_PUBLIC_API_ESTOQUE_TOKEN}
    restart: always
    ports:
      - "3001:3000" # Liberado na porta 3001 para não conflitar no seu SSH
    environment:
      TZ: "America/Sao_Paulo"
      # Conecta no 'db' internamente no banco 'helpdesk'
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/helpdesk?schema=public"
      # URL para o Next.js conversar com o Estoque na rede interna do Docker
      API_ESTOQUE_URL: "http://estoque:8080"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      NEXT_PUBLIC_API_ESTOQUE_TOKEN: ${NEXT_PUBLIC_API_ESTOQUE_TOKEN}
      API_ESTOQUE_TOKEN: ${API_ESTOQUE_TOKEN}
    depends_on:
      - db

  # 3. ESTOQUE (SPRING BOOT)
  estoque:
    container_name: estoque_api
    build:
      context: ./estoque
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      # A MÁGICA AQUI: Conecta no mesmo serviço 'db', mas no banco 'suprimentos'
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/helpdesk"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      API_ESTOQUE_TOKEN: ${API_ESTOQUE_TOKEN}
      # Cria as tabelas do estoque automaticamente
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  postgres_data: